services:
    coldfusion:
        container_name: coldfusion
        image: adobecoldfusion/coldfusion:latest
        ports:
        - "8500:8500"
        volumes:
        - ./app:/app
        env_file:
        - coldfusion.env
        healthcheck:
           test: curl -f http://localhost:8500/ 
           interval: 1m
           timeout: 3s
        networks:
        - webnet

    sqlserver:
        container_name: sqlserver
        image: mcr.microsoft.com/azure-sql-edge:latest
        environment:
        - ACCEPT_EULA=1
        - MSSQL_SA_PASSWORD=saPassword123
        ports:
        - "1433:1433"
        volumes:
        - .sql_data:/var/opt/mssql
        networks:
        - webnet
networks:
    webnet: 